stages:
  - setup
  - build

flutter_dependencies:
  stage: setup
  script:
    - echo "Run pub get and analyze"
    - pwd
    - which fastlane
    - flutter pub get
    - flutter analyze
  only:
    - merge_requests
  tags:
    - vietbq-runner

build_non_prod:
  stage: build
  tags:
    - vietbq-runner
  only:
    - /non\_prod\_version.*/
  script:
    - echo "Trigger by tag name to build non-prod version"
    - cd cicd
    - ./build_development_env_ios.sh

build_prod:
  stage: build
  tags:
    - vietbq-runner
  only:
    - /release\_version.*/
  script:
    - echo "Trigger by tag name to build prod version"
    - cd cicd
    - ./build_pilot_ios.sh